const books = [
  {
    id: 1,
    title: 'z',
    author: 'Author 1',
    price: '$10.99',
    description: 'Description of Book 1',
    image: 'book1.jpg',
  },
  {
    id: 2,
    title: 'Book 2',
    author: 'Author 2',
    price: '$12.99',
    description: 'Description of Book 2',
    image: 'book2.jpg',
  },
  {
    id: 3,
    title: 'Book 3',
    author: 'Author 3',
    price: '$8.99',
    description: 'Description of Book 3',
    image: 'book3.jpg',
  },
  {
    id: 4,
    title: 'Book 4',
    author: 'Author 4',
    price: '$14.99',
    description: 'Description of Book 4',
    image: 'book4.jpg',
  },
  {
    id: 5,
    title: 'Book 5',
    author: 'Author 5',
    price: '$9.99',
    description: 'Description of Book 5',
    image: 'book5.jpg',
  },
  {
    id: 6,
    title: 'Book 6',
    author: 'Author 6',
    price: '$11.99',
    description: 'Description of Book 6',
    image: 'book6.jpg',
  },
  {
    id: 7,
    title: 'Book 7',
    author: 'Author 7',
    price: '$13.99',
    description: 'Description of Book 7',
    image: 'book7.jpg',
  },
  {
    id: 8,
    title: 'Book 8',
    author: 'Author 8',
    price: '$15.99',
    description: 'Description of Book 8',
    image: 'book8.jpg',
  },
  {
    id: 9,
    title: 'Book 9',
    author: 'Author 9',
    price: '$10.99',
    description: 'Description of Book 9',
    image: 'book9.jpg',
  },
  {
    id: 10,
    title: 'Book 10',
    author: 'Author 10',
    price: '$12.99',
    description: 'Description of Book 10',
    image: 'book10.jpg',
  },
  {
    id: 11,
    title: 'Book 11',
    author: 'Author 11',
    price: '$8.99',
    description: 'Description of Book 11',
    image: 'book11.jpg',
  },
  {
    id: 12,
    title: 'Book 12',
    author: 'Author 12',
    price: '$14.99',
    description: 'Description of Book 12',
    image: 'book12.jpg',
  },
  {
    id: 13,
    title: 'Book 13',
    author: 'Author 13',
    price: '$9.99',
    description: 'Description of Book 13',
    image: 'book13.jpg',
  },
  {
    id: 14,
    title: 'Book 14',
    author: 'Author 14',
    price: '$11.99',
    description: 'Description of Book 14',
    image: 'book14.jpg',
  },
  {
    id: 15,
    title: 'Book 15',
    author: 'Author 15',
    price: '$13.99',
    description: 'Description of Book 15',
    image: 'book15.jpg',
  },
  {
    id: 16,
    title: 'Book 16',
    author: 'Author 16',
    price: '$15.99',
    description: 'Description of Book 16',
    image: 'book16.jpg',
  },
  {
    id: 17,
    title: 'Book 17',
    author: 'Author 17',
    price: '$10.99',
    description: 'Description of Book 17',
    image: 'book17.jpg',
  },
  {
    id: 18,
    title: 'Book 18',
    author: 'Author 18',
    price: '$12.99',
    description: 'Description of Book 18',
    image: 'book18.jpg',
  },
  {
    id: 19,
    title: 'Book 19',
    author: 'Author 19',
    price: '$8.99',
    description: 'Description of Book 19',
    image: 'book19.jpg',
  },
  {
    id: 20,
    title: 'Book 20',
    author: 'Author 20',
    price: '$14.99',
    description: 'Description of Book 20',
    image: 'book20.jpg',
  },
  {
    id: 20,
    title: 'Book 20',
    author: 'Author 20',
    price: '$14.99',
    description: 'Description of Book 20',
    image: 'book20.jpg',
  },
  
];

export default books;
